### ISSUE TITLE
Aggregates can return unsafe integers

### ISSUE THREAD

**Issue by acdibble** [graphile/pg-aggregates#39]
### Summary

We have some sums of numeric columns that exceed the range of safe integers in JS. The [sum aggregator](https://github.com/graphile/pg-aggregates/blob/main/src/AggregateSpecsPlugin.ts#L54) and others build the JSON object with the number directly without seeing if it's within bounds.

Obviously postgraphile and this plugin aren't limited to just the JS ecosystem, but a large consumer of postgraphile are surely browsers.

### Steps to reproduce

Query an aggregate such that it returns a number larger than 2^53 - 1.

### Expected results

A result such as:

```json
{ "@sum": { "@amount": "29531249370647025750" } }
```

### Actual results

```json
{ "@sum": { "@amount": 29531249370647025750 } }
```

Which when parsed in JS yields (note the lost precision):

```js
> JSON.parse('{"@sum":{"@amount":29531249370647025750}}')
{ '@sum': { '@amount': 29531249370647028000 } }
```

### Possible Solution

I'm willing to submit a patch to fix this issue, but need some direction on how to best implement this functionality.

To me, it seems that numerics, due to their arbitrary length both before and after the decimal place, should always be cast to text before getting returned, but this isn't backwards compatible.

Alternatively, additional aggregates could be introduced that can be used to cast to text when the aggregates are likely to exceed safe bounds and it's up to the consumer to parse those into numbers.

**Comment by benjie** [comment]
Is the GraphQL type (BigInt/BigFloat/etc) correct? If so the issue is just that we’re not correctly casting it to text in postgres and fixing that should be non-breaking. If the types in the schema are wrong then it’s more problematic…

**Comment by acdibble** [comment]
The type of the column in question is `numeric(30,0)`. When querying this field with postgraphile, it is cast to text which seems to be the correct behavior. The aggregations of this column are not cast to text by this plugin.

**Comment by benjie** [comment]
The issue seems to be that the "tweaks" aren't being applied (where a fragment is cast to `::text` or converted to JSON or whatever to make it safe).

`build.pgTweakFragmentForTypeAndModifier` is defined here:
https://github.com/graphile/graphile-engine/blob/516e8f7aab03b371626ee84bd2160b31d949dd55/packages/graphile-build-pg/src/plugins/PgTypesPlugin.js#L293

It takes `fragment, type, typeModifier = null, resolveData`. I can't remember why it needs `resolveData`... Hopefully you can ignore that for the aggregates, or pass a stub value. Please investigate though.

`fragment` would be the `sqlAggregate` here: https://github.com/graphile/pg-aggregates/blob/8c2acd19130e290504e3e4ea884244fe5e4bf399/src/AddAggregateTypesPlugin.ts#L201

`type` and `typeModifier` are defined here: https://github.com/graphile/pg-aggregates/blob/8c2acd19130e290504e3e4ea884244fe5e4bf399/src/AddAggregateTypesPlugin.ts#L175

You may also need to apply the same changes for procs, though I suspect this is already handled elsewhere.

Please make sure that these fixes are covered by tests - I'd recommend you start by writing failing tests (both of procs and regular SQL), commit that in its own commit, and then start applying the changes to fix the tests.

> The type of the column in question is numeric(30,0). When querying this field with postgraphile, it is cast to text which seems to be the correct behavior. The aggregations of this column are not cast to text by this plugin.

To be clear, I was asking about the types that represent these aggregates in the GraphQL schema itself - i.e. what is the type of the aggregate field for this in GraphiQL. If those types are wrong then that's an issue with `pgTypeAndModifierModifier`, but I strongly suspect that the types in the GraphQL schema are correct and it's merely the generated SQL that is incorrect.

**Comment by benjie** [comment]
Ugh it seems that this module doesn't actually _have_ any tests. 🤦‍♂️  Clearly ran out of time when implementing it. Okay skip the tests.

**Comment by acdibble** [comment]
> To be clear, I was asking about the types that represent these aggregates in the GraphQL schema itself - i.e. what is the type of the aggregate field for this in GraphiQL. If those types are wrong then that's an issue with pgTypeAndModifierModifier, but I strongly suspect that the types in the GraphQL schema are correct and it's merely the generated SQL that is incorrect.

Gotcha, that is `BigFloat` so that part is working correctly.

I'll look into adding some tweakers for the aggregates, thanks!

**Comment by benjie** [comment]
Can confirm that this definitely returns a string in V5 :+1:

**Comment by acdibble** [comment]
Great! Hope to check it out soon

**Comment by stwiname** [comment]
@benjie we're still stuck on V4. Is there any direction you could point us in for patching this ourselves?

**Comment by benjie** [comment]
@stwiname did you see https://github.com/graphile/pg-aggregates/issues/39#issuecomment-1404737719 ?

**Comment by acdibble** [comment]
> [@benjie](https://github.com/benjie) we're still stuck on V4. Is there any direction you could point us in for patching this ourselves?

Here's the patch we used:
```patch
diff --git a/dist/AggregateSpecsPlugin.js b/dist/AggregateSpecsPlugin.js
index b5ba4d49dd3c776c3ed78748c8b1ed72f0920cba..e8f652e42117002b451f970b96c0bf22765f0cec 100644
--- a/dist/AggregateSpecsPlugin.js
+++ b/dist/AggregateSpecsPlugin.js
@@ -33,7 +33,7 @@ const AggregateSpecsPlugin = (builder) => {
                 HumanLabel: "Sum",
                 isSuitableType: isNumberLike,
                 // I've wrapped it in `coalesce` so that it cannot be null
-                sqlAggregateWrap: (sqlFrag) => sql.fragment `coalesce(sum(${sqlFrag}), 0)`,
+                sqlAggregateWrap: (sqlFrag) => sql.fragment `coalesce(sum(${sqlFrag}), 0)::TEXT`,
                 isNonNull: true,
                 // A SUM(...) often ends up significantly larger than any individual
                 // value; see
```

**Comment by stwiname** [comment]
This isn't compatible with `postgraphile-plugin-connection-filter` and the `greaterThan` filter because it forces the values to compare strings. 

We will try and come up with another solution

> > [@benjie](https://github.com/benjie) we're still stuck on V4. Is there any direction you could point us in for patching this ourselves?
> 
> Here's the patch we used:
> 
> diff --git a/dist/AggregateSpecsPlugin.js b/dist/AggregateSpecsPlugin.js
> index b5ba4d49dd3c776c3ed78748c8b1ed72f0920cba..e8f652e42117002b451f970b96c0bf22765f0cec 100644
> --- a/dist/AggregateSpecsPlugin.js
> +++ b/dist/AggregateSpecsPlugin.js
> @@ -33,7 +33,7 @@ const AggregateSpecsPlugin = (builder) => {
>                  HumanLabel: "Sum",
>                  isSuitableType: isNumberLike,
>                  // I've wrapped it in `coalesce` so that it cannot be null
> -                sqlAggregateWrap: (sqlFrag) => sql.fragment `coalesce(sum(${sqlFrag}), 0)`,
> +                sqlAggregateWrap: (sqlFrag) => sql.fragment `coalesce(sum(${sqlFrag}), 0)::TEXT`,
>                  isNonNull: true,
>                  // A SUM(...) often ends up significantly larger than any individual
>                  // value; see

**Comment by acdibble** [comment]
We used this patch with `postgraphile-plugin-connection-filter`. It just casts the result of the sum aggregation to a string value. It doesn't affect the filtering which is done at the column level as far as I understand.
